export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{
          backgroundImage: "url('/assets/icons/17.jpg')", // Replace with the actual image path
          backgroundSize: "cover", // Ensure the image covers the whole screen
          backgroundPosition: "center", // Center the background image
        }}
      >
        {children}
      </body>
    </html>
  );
}
